from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


def run_cli(
    project_root: Path,
    generated_dir: str,
    rs: int,
    sm: int,
    difficulty: str,
) -> Dict[str, Any]:
    """
    Calls scripts/summon_cli.py and returns parsed JSON.
    Uses subprocess to avoid import/path issues.
    """
    cli_path = project_root / "scripts" / "summon_cli.py"
    if not cli_path.exists():
        raise FileNotFoundError(f"Cannot find summon_cli.py at: {cli_path}")

    cmd = [
        sys.executable,
        str(cli_path),
        "--generated-dir",
        str(generated_dir),
        "--skill",
        "raise_skeleton",
        "--slvl",
        str(rs),
        "--blvl",
        str(rs),
        "--difficulty",
        str(difficulty),
        "--set",
        f"skeleton_mastery.lvl={sm}",
        "--set",
        f"skeleton_mastery.blvl={sm}",
        "--json",
    ]

    proc = subprocess.run(
        cmd,
        cwd=str(project_root),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    if proc.returncode != 0:
        raise RuntimeError(
            "summon_cli.py failed\n"
            f"CMD: {' '.join(cmd)}\n"
            f"STDOUT:\n{proc.stdout}\n"
            f"STDERR:\n{proc.stderr}\n"
        )

    # Some shells prepend garbage before JSON; find first '{'
    out = proc.stdout
    start = out.find("{")
    if start == -1:
        raise ValueError(f"CLI output did not contain JSON.\nSTDOUT:\n{out}\nSTDERR:\n{proc.stderr}")
    out = out[start:]
    return json.loads(out)


def pick_breakdown_value(payload: Dict[str, Any], label: str) -> Optional[Dict[str, Any]]:
    for row in payload.get("breakdown", []):
        if row.get("label") == label:
            return row.get("value")
    return None


def build_expected(payload: Dict[str, Any]) -> Dict[str, Any]:
    expected = {
        "final": payload.get("final", {}),
        "extract": {
            "rs_internal_flat": None,
            "total_skill_bonus": None,
        },
    }

    rs_internal = pick_breakdown_value(payload, "RS internal flat (seg5)")
    if isinstance(rs_internal, dict):
        expected["extract"]["rs_internal_flat"] = rs_internal.get("rs_internal_flat")

    skill_bonus = pick_breakdown_value(payload, "Skill bonus (flat)")
    if isinstance(skill_bonus, dict):
        expected["extract"]["total_skill_bonus"] = skill_bonus.get("total_skill_bonus")

    return expected


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generated-dir", required=True, help="Path to generated dataset dir")
    ap.add_argument(
        "--cases",
        default=str(Path("scripts/tests/cases_raise_skeleton.json")),
        help="Path to cases JSON",
    )
    ap.add_argument(
        "--out",
        default=str(Path("scripts/tests/baseline_raise_skeleton.json")),
        help="Where to write baseline JSON",
    )
    args = ap.parse_args()

    project_root = Path.cwd()
    cases_path = project_root / args.cases
    out_path = project_root / args.out

    cases_doc = json.loads(cases_path.read_text(encoding="utf-8"))
    cases: List[Dict[str, Any]] = cases_doc.get("cases", [])

    baseline: Dict[str, Any] = {
        "meta": {
            "schema": "summon_baseline.v1",
            "skill": "raise_skeleton",
            "generated_dir": str(args.generated_dir),
            "notes": "Autogenerated from current engine output via summon_cli.py",
        },
        "cases": [],
    }

    for c in cases:
        case_id = c["id"]
        rs = int(c["rs"])
        sm = int(c["sm"])
        diff = str(c.get("difficulty", "hell"))

        payload = run_cli(project_root, args.generated_dir, rs, sm, diff)
        expected = build_expected(payload)

        baseline["cases"].append(
            {
                "id": case_id,
                "rs": rs,
                "sm": sm,
                "difficulty": diff,
                "expected": expected,
            }
        )

        print(f"[OK] {case_id}: RS={rs} SM={sm} diff={diff} -> final={expected['final']}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWrote baseline: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
