from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


# Hard pointy jsou v D2 omezene sloupcem maxlvl v skills.txt (= 20 pro vsechny
# necro summon skilly). Efektivni uroven nad 20 pochazi z +skills na itemech,
# ktere zadne hard pointy nepridavaji. Baseline pripady proto deklaruji base
# uroven zastropovanou na 20, ne rovnou efektivni urovni.
#
# Na soucasne vysledky to nema vliv - modely Raise Skeleton ani Skeletal Mage
# hodnotu blvl nectou. Zacne na tom zaviset az synergie (viz
# docs/SKILLS_PROJECTION.md sekce 5), ktere se pocitaji prave z hard pointu.
HARD_POINT_CAP = 20


def base_level(effective_level: int) -> int:
    """Base (hard-point) uroven odpovidajici dane efektivni urovni."""
    return min(int(effective_level), HARD_POINT_CAP)


def run_cli(
    project_root: Path,
    generated_dir: str,
    rsm: int,
    sm: int,
    difficulty: str,
) -> Dict[str, Any]:
    """
    Calls scripts/summon_cli.py and returns parsed JSON.
    Uses subprocess to avoid import/path issues.
    """
    cli_path = project_root / "scripts" / "summon_cli.py"
    if not cli_path.exists():
        raise FileNotFoundError(f"Cannot find summon_cli.py at: {cli_path}")

    cmd = [
        sys.executable,
        str(cli_path),
        "--generated-dir",
        str(generated_dir),
        "--skill",
        "raise_skeletal_mage",
        "--slvl",
        str(rsm),
        "--blvl",
        str(base_level(rsm)),
        "--difficulty",
        str(difficulty),
        "--set",
        f"skeleton_mastery.lvl={sm}",
        "--set",
        f"skeleton_mastery.blvl={base_level(sm)}",
        "--json",
    ]

    proc = subprocess.run(
        cmd,
        cwd=str(project_root),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    if proc.returncode != 0:
        raise RuntimeError(
            "summon_cli.py failed\n"
            f"CMD: {' '.join(cmd)}\n"
            f"STDOUT:\n{proc.stdout}\n"
            f"STDERR:\n{proc.stderr}\n"
        )

    # Some shells prepend garbage before JSON; find first '{'
    out = proc.stdout
    start = out.find("{")
    if start == -1:
        raise ValueError(f"CLI output did not contain JSON.\nSTDOUT:\n{out}\nSTDERR:\n{proc.stderr}")
    out = out[start:]
    return json.loads(out)


def dig(d: Dict[str, Any], path: str) -> Optional[Any]:
    """
    Safe getter for nested dicts using dot paths.
    Example: "final.elemental_damage.poison.total_min"
    """
    cur: Any = d
    for part in path.split("."):
        if not isinstance(cur, dict):
            return None
        if part not in cur:
            return None
        cur = cur[part]
    return cur


def build_expected(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Store full final output + a small set of internal signals (early warning).
    """
    final = payload.get("final", {})

    extract = {
        "rsl": final.get("rsl"),
        "summon_count": final.get("summon_count", final.get("count")),
        "cold_duration_sec": dig(payload, "final.elemental_damage.cold.duration_sec"),
        "poison_total_min": dig(payload, "final.elemental_damage.poison.total_min"),
        "poison_total_max": dig(payload, "final.elemental_damage.poison.total_max"),
    }

    return {
        "final": final,
        "extract": extract,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generated-dir", required=True, help="Path to generated dataset dir")
    ap.add_argument(
        "--cases",
        default=str(Path("scripts/tests/cases_raise_skeletal_mage.json")),
        help="Path to cases JSON",
    )
    ap.add_argument(
        "--out",
        default=str(Path("scripts/tests/baseline_raise_skeletal_mage.json")),
        help="Where to write baseline JSON",
    )
    args = ap.parse_args()

    project_root = Path.cwd()
    cases_path = project_root / args.cases
    out_path = project_root / args.out

    cases_doc = json.loads(cases_path.read_text(encoding="utf-8"))
    cases: List[Dict[str, Any]] = cases_doc.get("cases", [])

    baseline: Dict[str, Any] = {
        "meta": {
            "schema": "summon_baseline.v1",
            "skill": "raise_skeletal_mage",
            "generated_dir": str(args.generated_dir),
            "notes": "Autogenerated from current engine output via summon_cli.py",
        },
        "cases": [],
    }

    for c in cases:
        case_id = c["id"]
        rsm = int(c["rsm"])
        sm = int(c["sm"])
        diff = str(c.get("difficulty", "hell"))

        payload = run_cli(project_root, args.generated_dir, rsm, sm, diff)
        expected = build_expected(payload)

        baseline["cases"].append(
            {
                "id": case_id,
                "rsm": rsm,
                "sm": sm,
                "difficulty": diff,
                "expected": expected,
            }
        )

        print(f"[OK] {case_id}: RSM={rsm} SM={sm} diff={diff} -> rsl={expected['extract']['rsl']}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWrote baseline: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
